client/src/index.tsx
client/src/redux/store.ts

```
// store.ts 리덕스 스토어
const store = configureStore({
reducer: {
reviewModal,
},
});
```
```
// reviewModal.ts 리덕스 리듀서
const reviewModalSlice = createSlice({
name: 'reviewModal',
initialState: { status: false },
reducers: {
open: (state) => {
state.status = true;
},
close: (state) => {
state.status = false;
},
},
});
const { open, close } = reviewModalSlice.actions;
export const reviewModalAction = { open, close };
export default reviewModalSlice.reducer;
```
```
// ReviewRegister.tsx 리액트 컴포넌트 실사용
export default function ReviewRegister() {
const { reviewModal } = useAppSelector((state) => state);
const dispatch = useAppDispatch();
dispatch(reviewModalAction.open());
return <></>;
}
```

feat: 리덕스 스토어 생성

---

client/src/pages/Movie.tsx
client/src/pages/styles/Movie.styled.ts

- 스타일드 컴포넌트 네이밍 Styled 제거 예정
- 브랜치명 변경 fe/feat-movie-info -> fe/feat-movie-info-ui

feat: 영화 정보 컴포넌트 UI 구현

---

client/src/components/movie/ConfirmModal.tsx
client/src/components/movie/ReviewRegisterModal.tsx
client/src/components/styles/ConfirmModal.styled.ts
client/src/components/styles/Rating.styled.ts
client/src/components/styles/ReviewRegisterModal.styled.ts
client/src/index.css
client/src/pages/Movie.tsx
client/src/pages/styles/Movie.styled.ts

- index.css color 변수 생성
- 네이밍 컨벤션 Styled~ 제거

feat: 스타일링 수정

---

client/src/components/main/MovieRank.tsx/Card.tsx
client/src/components/main/MovieRank.tsx/Slider.tsx
client/src/components/main/MovieRank.tsx/Topmovie.tsx
client/src/components/main/Tabmovie.tsx/Botmovietab.tsx
client/src/components/main/Tabmovie.tsx/Tab.tsx
client/src/components/main/Tabmovie.tsx/TabCard.tsx
client/src/components/main/Tabmovie.tsx/Tabslider.tsx
client/src/components/styles/rankmovie/Card.styled.ts
client/src/components/styles/rankmovie/Slider.styled.ts
client/src/components/styles/rankmovie/Topmovie.styled.ts
client/src/components/styles/tabmovie/Botmovie.styled.ts
client/src/components/styles/tabmovie/Tab.styled.ts
client/src/components/styles/tabmovie/Tabcard.styled.ts
client/src/dummy/dummyNewMovies.ts
client/src/dummy/dummyPopular.ts
client/src/dummy/dummyUpcoming.ts
client/src/pages/Main.tsx
client/src/pages/styles/Main.styled.ts

feat: 메인페이지 tab 영화 목록 UI, 캐러셀 UI

feat: 메인페이지 tab 영화 목록 UI

---

client/src/components/main/Tabmovie.tsx/Tab.tsx

fix: 탭 다른 타이틀 눌렀을때 리셋

---

server/src/main/java/com/cinemaprincess/genre/GenreDto.java
server/src/main/java/com/cinemaprincess/movie/dto/MovieDetailResponseDto.java
server/src/main/java/com/cinemaprincess/movie/entity/MovieDetail.java
server/src/main/java/com/cinemaprincess/movie/entity/MovieDetailWatchProvider.java
server/src/main/java/com/cinemaprincess/movie/mapper/MovieMapper.java
server/src/main/java/com/cinemaprincess/movie/repository/MovieDetailRepository.java
server/src/main/java/com/cinemaprincess/movie/repository/MovieJdbcRepository.java
server/src/main/java/com/cinemaprincess/movie/save/SaveMovieDetail.java
server/src/main/java/com/cinemaprincess/movie/save/SaveMovieList.java
server/src/main/java/com/cinemaprincess/watch_provider/WatchProvider.java
server/src/main/java/com/cinemaprincess/watch_provider/WatchProviderDto.java
server/src/main/java/com/cinemaprincess/watch_provider/WatchProviderRepository.java
server/src/main/java/com/cinemaprincess/watch_provider/WatchProviderService.java

1. 영화 상세조회 시 장르목록 표시
2. 장르 리스트 api로 받아와서 미리 저장
3. watchprovider 도메인 부분 구현

feat: WatchProvider 구현

---

client/src/components/share/Footer.tsx
client/src/components/share/Header.tsx
client/src/components/signup/SignupForm1.tsx
client/src/components/styles/Header.styled.ts
client/src/components/styles/SignupForm1.styled.ts
client/src/pages/Signup.tsx
client/src/redux/reducers/singupSlice.ts

모달창의 백그라운드 css가 페이지 내용 뒤로 가는 현상 해결중
회원가입 컴포넌트에서 해결 OR 루트 페이지의 스타일에서 해결

fix: Header의 회원가입 버튼에 모달 컴포넌트 적용

---

client/src/components/login/loginForm.tsx
client/src/components/share/Header.tsx
client/src/components/styles/Header.styled.ts
client/src/components/styles/LoginForm.styled.ts
client/src/components/styles/Searchbar.styled.ts
client/src/components/styles/SignupForm1.styled.ts
client/src/pages/Login.tsx
client/src/pages/styles/Login.styled.ts

feat: LoginForm생성, 모달창 관련 수정, 찜한 영화 버튼 수정

---

server/src/main/java/com/cinemaprincess/exception/ExceptionCode.java
server/src/main/java/com/cinemaprincess/movie/service/MovieService.java
server/src/main/java/com/cinemaprincess/review/dto/ReviewPostDto.java
server/src/main/java/com/cinemaprincess/review/dto/ReviewResponseDto.java
server/src/main/java/com/cinemaprincess/review/dto/ReviewVoteDto.java
server/src/main/java/com/cinemaprincess/review/entity/Review.java
server/src/main/java/com/cinemaprincess/review/entity/ReviewVote.java
server/src/main/java/com/cinemaprincess/review/repository/ReviewVoteRepository.java
server/src/main/java/com/cinemaprincess/review/service/ReviewService.java

중복 리뷰가 작성되지 않는 오류 수정했습니다.
Vote와 관련된 것은 아직 구현중이라 무시하셔도 될 것 같습니다!

Fix: review bug

---

client/src/components/styles/watchlist/WatchDrop.styled.ts
client/src/components/watch/WatchDrop.tsx
client/src/dummy/dummyTop.ts
client/src/pages/Main.tsx
client/src/pages/Watchlist.tsx

feat: 와치리스트 페이지 드롭다운 메뉴, 필터 UI

feat: 와치리스트 페이지 드롭다운 메뉴, 필터 UI

---

client/src/components/watch/WatchDrop.tsx
client/src/dummy/dummyTop.ts

 feat: 와치리스트 무한스크롤

---

client/src/components/login/loginForm.tsx
client/src/components/share/Searchbar.tsx
client/src/components/signup/SignupForm1.tsx
client/src/pages/Statistics.tsx
client/src/redux/reducers/authSlice.ts
client/src/redux/store.ts

통계페이지(전체) ui 생성
검색창 핸들러 수정
로그인 유효성 검사 수정
Accesstoken 발급 수정

feat: 통계 페이지 ui 생성

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/api/statistics.ts
client/src/pages/YearlyGenres.tsx
client/src/pages/styles/YearlyGenres.styled.ts

feat: 연도별 장르 통계페이지 UI 구현

---

client/package-lock.json
client/package.json
client/src/components/login/loginForm.tsx
client/src/components/share/Header.tsx

jwt-decode 라이브러리 설치
로그인 / 로그아웃시 토큰, userId(파싱) 각각 저장 / 삭제

fix: 토큰, userId 관리 수정

---

client/src/components/login/loginForm.tsx
client/src/components/share/Header.tsx
client/src/redux/reducers/isLogin.ts

fix: 로그인 토큰 수정

---

client/src/api/getSearch.ts
client/src/components/share/Pagination.tsx
client/src/components/share/Searchbar.tsx
client/src/components/styles/Searchbar.styled.ts
client/src/pages/Search.tsx
client/src/redux/reducers/searchSlice.ts
client/src/redux/store.ts

1페이지만 영화를 가져오는 문제
영화 포스터 엑스박스 문제
머지 후 다른 브랜치에서 수정

feat: 검색페이지 기능 구현

---

server/src/main/java/com/cinemaprincess/auth/config/SecurityConfiguration.java
server/src/main/java/com/cinemaprincess/review/service/ReviewService.java
server/src/main/java/com/cinemaprincess/watchlist/service/WatchlistService.java
server/src/main/resources/application.yml

Fix: 와치리스트 삭제 오류 및 무비 랭크 접근권한 수정

Fix: 와치리스트 삭제 오류 및 무비 랭크 접근권한 수정

---

client/src/api/getMovierank.ts
client/src/components/main/movierank/Card.tsx
client/src/components/main/movierank/Topmovie.tsx
client/src/components/styles/rankmovie/Card.styled.ts
client/src/pages/Movie.tsx
client/src/pages/Search.tsx
client/src/redux/reducers/movierank.ts
client/src/redux/store.ts

feat: 메인페이지 박스오피스 순위 api 기능

---

server/src/main/java/com/cinemaprincess/exception/ExceptionCode.java
server/src/main/java/com/cinemaprincess/movie/controller/MovieController.java
server/src/main/java/com/cinemaprincess/review/controller/ReviewController.java
server/src/main/java/com/cinemaprincess/review/dto/ReviewResponseDto.java
server/src/main/java/com/cinemaprincess/review/service/ReviewService.java

Fix: 리뷰에 대한 유저의 종아요 여부 표시

---

client/src/App.tsx
client/src/pages/Statistics.tsx
client/src/pages/Statisticsusers.tsx
client/src/pages/styles/Statisticsusers.styled.ts

feat: 성별, 연령별 장르 선호도 통계페이지 ui, 통계페이지 링크 수정

---

client/src/pages/Movie.tsx

fix: 비슷한 영화 추천 컴포넌트 수정

---

client/src/components/main/monthmovie/Monthmovie.tsx

 fix: 이번달 상영작 링크 이동

---

client/src/pages/Movie.tsx

fix: 영화 트레일러 영상 경로 수정

---

client/src/components/login/Googlelogin.tsx
client/src/components/login/OauthHandler.tsx
client/src/components/signup/SignupForm1.tsx

fix: 회원가입 경고메세지 수정, Oauth 로그인 수정중

---

client/src/api/getMonthly.ts
client/src/components/main/monthmovie/Monthmovie.tsx
client/src/redux/reducers/yearlySlice.ts
client/src/redux/store.ts

 fix: 이번달 상영작 -> 올해 추천작 수정

---

client/src/styles/components/main/monthmovie/Monthcard.ts
client/src/styles/components/main/rankmovie/Card.styled.ts
client/src/styles/components/main/rankmovie/Topmovie.styled.ts
client/src/styles/components/main/tabmovie/Tabcard.styled.ts
client/src/styles/pages/Main.styled.ts

fix: 메인페이지 화면 수정

---

client/src/styles/components/main/rankmovie/Card.styled.ts

 fix: 순위 수정

---

client/src/components/watch/WatchDrop.tsx

fix: 무한스크롤 버그 수정
